[workspace]
resolver = "2"
members = ["bin/cli", "crates/core"]

    [workspace.dependencies]
    # error handling
    anyhow = "1.0"
    thiserror = "1.0"
    # logging
    log = { version = "0.4" }
    env_logger = "0.11"
    # image
    image = "0.25"
