[package]
name = "lenticular-image-tool-cli"
version = "0.2.2"
edition = "2021"

[dependencies]
lenticular_core = { path = "../../crates/core" }
anyhow = { workspace = true }
log = { workspace = true }
tiff = { workspace = true }
env_logger = "0.11"
clap = { version = "4.5.18", features = ["derive"] }
num = "0.4.3"
