[package]
name = "testing"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
log.workspace = true
tiff = { workspace = true }
# image = { workspace = true }
ndarray = { version = "0.16.1", features = ["rayon"] }
fast_image_resize = { version = "3" }
env_logger = "0.11"
anyhow.workspace = true

[dev-dependencies]
env_logger = "0.11"
