[package]
name = "lenticular-image-tool"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
image = { workspace = true }
log = { workspace = true }
dialoguer = { version = "0.11", features = ["completion"] }
dotenvy = "0.15"
env_logger = "0.11"
